{
 "title": "Open Analytics Dashboard",
 "description": "Example dashboard for Open Analytics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "session",
    "label": "Session",
    "query": {
     "query": "SELECT DISTINCT sessionId FROM default.epas_default"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='countingevents', user=1 */\nSELECT\n  COUNT(DISTINCT sessionId) AS \"Unique Sessions\"\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime(1761544748780 / 1000)\n  AND timestamp <= toDateTime(1761566348780 / 1000)",
     "query": "SELECT\n  COUNT(DISTINCT sessionId) AS \"Unique Sessions\"\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to / 1000)",
     "rawQuery": "/* grafana dashboard=counting events, user=1 */\nSELECT\n  COUNT(DISTINCT sessionId) AS \"Unique Sessions\"\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime(1746177873548 / 1000)\n  AND timestamp <= toDateTime(1746181473548 / 1000)",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Device Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  deviceType   AS category,\n  COUNT(*)     AS value\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to   / 1000)\n  AND event = 'metadata'\n  AND deviceType IS NOT NULL\nGROUP BY\n  deviceType\n",
     "rawQuery": "/* grafana dashboard=counting events, user=1 */\nSELECT\n  deviceType   AS category,\n  COUNT(*)     AS value\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime(1746153146537 / 1000)\n  AND timestamp <= toDateTime(1746196346537   / 1000)\n  AND event = 'metadata'\n  AND deviceType IS NOT NULL\n\nGROUP BY\n  deviceType",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Initiated Sessions (5mins)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  toStartOfInterval(toDateTime(timestamp), INTERVAL 5 MINUTE) AS time,\n  'initiated_sessions' AS metric,\n  COUNT(DISTINCT sessionId) AS value\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to / 1000)\n  AND event = 'init'\nGROUP BY\n  time,\n  metric\nORDER BY\n  time",
     "rawQuery": "/* grafana dashboard=counting events, user=1 */\nSELECT\n  toStartOfInterval(toDateTime(timestamp), INTERVAL 5 MINUTE) AS time,\n  'initiated_sessions' AS metric,\n  COUNT(DISTINCT sessionId) AS value\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime(1746182531238 / 1000)\n  AND timestamp <= toDateTime(1746183431238 / 1000)\n  AND eventT = 'init'\nGROUP BY\n  time,\n  metric\nORDER BY\n  time",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Events Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Open Analytics Dashboard', user=1 */\nSELECT\n  toStartOfMinute(timestamp) AS time,\n  event,\n  count(*) AS event_count\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime(1761547323915 / 1000)\n  AND timestamp <= toDateTime(1761568923915 / 1000)\nGROUP BY time, event\nORDER BY time ASC, event",
     "query": "SELECT\n  toStartOfMinute(timestamp) AS time,\n  event,\n  count(*) AS event_count\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime($__from / 1000)\n  AND timestamp <= toDateTime($__to / 1000)\nGROUP BY time, event\nORDER BY time ASC, event\n",
     "rawQuery": "/* grafana dashboard=counting events, user=1 */\nSELECT\n  toStartOfMinute(timestamp) AS t,\n  event,\n  count(*) AS event_count\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime(1746180516436 / 1000)\n  AND timestamp <= toDateTime(1746181416436 / 1000)\nGROUP BY t, event\nORDER BY t ASC, event",
     "round": "0s"
    }
   ]
  },
  { "title": "Follow session ($session)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Event Details for Session",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Open Analytics Dashboard', user=1 */\nSELECT *\nFROM default.epas_default\nWHERE sessionId = 'web-player-demo-1761566291637'\nORDER BY timestamp DESC",
     "query": "SELECT *\nFROM default.epas_default\nWHERE sessionId = $session\nORDER BY timestamp DESC",
     "rawQuery": "/* grafana dashboard=counting events, user=1 */\nSELECT\n  toStartOfInterval(toDateTime(timestamp), INTERVAL 5 MINUTE) AS time,\n  'initiated_sessions' AS metric,\n  COUNT(DISTINCT sessionId) AS value\nFROM default.epas_default\nWHERE\n  timestamp >= toDateTime(1746182531238 / 1000)\n  AND timestamp <= toDateTime(1746183431238 / 1000)\n  AND eventT = 'init'\nGROUP BY\n  time,\n  metric\nORDER BY\n  time",
     "round": "0s"
    }
   ]
  }
 ]
}